### PR TITLE
Set service_name and/or repo_token from .coveralls.yml regardless of if $COVERALLS_REPO_TOKEN is set

### LINKED ISSUE #273: Error: The commit wasn't found on the repo
I have a Coveralls setup that works perfectly in our public repos, but I used the same setup in a private repo, obviously adding the Coveralls token to Travis, and now I get this weird error about the commit not being found. Any ideas on what to do here? The PHPUnit coverage is reporting correctly to Coveralls but the JS coverage is failing. I've commented it out temporarily until I can find a solution, but that's not ideal.

```bash
> wp-scripts test-unit-js --coverage --coverageReporters=text-lcov | coveralls
TravisFoldPassesReporter
...1 passing test.
/home/travis/build/xwp/material-theme-builder-wp/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Bad response: 422 {"message":"Travis API Error: #\u003cCoveralls::Mash message=\"The job(285764075) couldn't be found\"\u003e. The commit  wasn't found on the repo xwp/material-theme-builder-wp","error":true}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! material-theme-builder-wp@ test:js:coveralls: `wp-scripts test-unit-js --coverage --coverageReporters=text-lcov | coveralls`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the material-theme-builder-wp@ test:js:coveralls script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2020-02-11T07_08_20_775Z-debug.log
```

### PR DESCRIPTION
**Pull request by benpetty**
- Set service_name and/or repo_token from .coveralls.yml regardless of if $COVERALLS_REPO_TOKEN is set
- Fixes #273, #161

### CODE REVIEW

**Comment by benpetty** [comment]
Fixes #273

**Comment by benpetty** [comment]
So this error actually is not just related to running tests in a Docker container inside travis, as we are having the same issues just running the tests in general on travis. Using travis -pro. Details here and others are having the same issue #273

**Comment by benpetty** [comment]
Also Fixes #161

**Comment by benpetty** [comment]
After testing my fork this does not fix the issue. Still getting random commit hash. Looking into a fix now!

**Comment by benpetty** [comment]
Confirmed this is working with `service_name: travis-pro` in coveralls.yml and `$COVERALLS_REPO_TOKEN` env var

**Comment by derekherman** [comment]
@benpetty thank you for working on a fix, legendary! Hopefully we can get a merge soon. @nickmerwin any idea when this might happen?

**Comment by derekherman** [comment]
I've just tested and this PR is working our private repo. ✅

File: lib/getOptions.js [hunk 1]
```diff
@@ -152,24 +149,41 @@ const getBaseOptions = cb => {
...
+      options.service_name = coveralls_yaml_conf.service_name;
+    }
+  }
+
+  // try to get the repo token as an environment variable
+  if (process.env.COVERALLS_REPO_TOKEN) {
+    options.repo_token = process.env.COVERALLS_REPO_TOKEN;
+  }
+
+  if (!options.repo_token) {
```
Comment (derekherman) [inline lib/getOptions.js]: I believe we could just do a sanity check here for private repos instead of always showing this warning.
```suggestion
  if ('travis-pro' === options.service_name && !options.repo_token) {
```

**Comment by derekherman** [comment]
I used this is different private repo and I'm getting this error, any suggestions?
```
Error: Command failed: git cat-file -p f32bc09e64a448f5d186a20d73a01bb2e330a6ac
fatal: Not a valid object name f32bc09e64a448f5d186a20d73a01bb2e330a6ac
    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:311:20)
    at Pipe.<anonymous> (net.js:668:12) {
  killed: false,
  code: 128,
  signal: null,
  cmd: 'git cat-file -p f32bc09e64a448f5d186a20d73a01bb2e330a6ac'
}
```

**Comment by derekherman** [comment]
Figured it out, the service name was set to the public `travis-ci` and not `travis-pro`. Disregard my last comment.

File: lib/getOptions.js [hunk 2]
```diff
@@ -152,24 +149,41 @@ const getBaseOptions = cb => {
...
+      options.service_name = coveralls_yaml_conf.service_name;
+    }
+  }
+
+  // try to get the repo token as an environment variable
+  if (process.env.COVERALLS_REPO_TOKEN) {
+    options.repo_token = process.env.COVERALLS_REPO_TOKEN;
+  }
+
+  if ('travis-pro' === options.service_name && !options.repo_token) {
```
Comment (derekherman) [inline lib/getOptions.js]: Technically this makes this code travis specific, which is probably not the expected behavior. We need a better way to know if the `COVERALLS_REPO_TOKEN` is required.

Comment (derekherman) [reply lib/getOptions.js]: Or remove this condition and notice entirely.

Comment (nickmerwin) [reply lib/getOptions.js]: @derekherman I think that's fine, since Travis was our first and only CI supported that doesn't require an explicit Repo token, so the special handling here isn't out of the ordinary.
